spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


